"""add embedding column to kb_docs

Revision ID: ad1ff3fadf8f
Revises: 833629bb3b3c
Create Date: 2026-07-27 03:10:52.098740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ad1ff3fadf8f'
down_revision: Union[str, Sequence[str], None] = '833629bb3b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('kb_docs', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_docs', 'embedding')
    # ### end Alembic commands ###
